# Generated by Django 3.0.6 on 2021-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=15)),
                ('timstamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
